version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "smart-review-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-i7x4oy0bii20"
s3_prefix = "smart-review-app"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
